### ISSUE TITLE
bad matching

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/skill-npr-news#100]
even if i pass an exact match for the short code sometimes the fuzzy_matching for the wrong feed will be given priority

example (in catalonia news feed), play CCMA news triggers CBC News

suggested fix: https://github.com/MycroftAI/skill-npr-news/pull/102/files#diff-8e2c1f727276d30ced72fa67cb848772a9802162bec39b42a8df5359fd063a4cR220

**Comment by ChanceNCounter** [comment]
Further finding: `KUOW` is a Seattle-area NPR station. When this skill is active, it captures the match and returns a different, foreign-language NPR station. If I disable this skill, TuneIn gets it. I've had inconsistent results with "94.9 FM Seattle" and such.

I don't know if this skill *should* be able to play NPR affiliates, but my expectation in this particular case was that a different skill would eat the match.
