### ISSUE TITLE
rss feed - bad assumption

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/skill-npr-news#101]
if a stream does not end with .mp3 it assumes it is a rss feed

This is a bad assumption, some streams are static and don't end with an extension

workaround: https://github.com/MycroftAI/skill-npr-news/pull/102/files#diff-8e2c1f727276d30ced72fa67cb848772a9802162bec39b42a8df5359fd063a4cR321

**Comment by krisgesling** [comment]
Closing as the Skill now uses feedparser to test if a url is an RSS feed.
