### ISSUE TITLE
FOX News Feed is broken

### ISSUE THREAD

**Issue by Olzeke51** [MycroftAI/skill-npr-news#115]
**Describe the bug**
Fox News is not being streamed, (and no visual ad either) -if 'what's the news'
IF 'play the news' - get the Fox splash screen visual but no audio
*
splash screen never cleared (?? dependent on audio stream) after a few minutes!!!

**To Reproduce**
1. Set News source to Fox News on home.mycroft.ai  account - skill setting
2. ASK for the news - two different results with two different requests

**Expected behavior**
an audio stream and a splash screen on the display in either case

**Log files**
SKills.log is upto 11MB - not sending right now

here they are
[big_files.tar.gz](https://github.com/MycroftAI/skill-npr-news/files/6759215/big_files.tar.gz)

**Environment (please complete the following information):**
 - Device type: Mark ][ -DevKit, on network cable
 - OS: default
 - Mycroft-core version: 21.02
 - Other versions: latest 07-03 01:30:22

**Additional context**
Been broken last 'latest' also

**Comment by Olzeke51** [comment]
added log files
*
was using the 'cli' tool on my DEV-kit when this showed up in the 'History' window  July 04 00:33 UTC approx.
""~~~~ng install_or_update on mycroft-npr-news: SkillModified(Uncommitted changes:
        MM dev_setup.sh
        MM doc/conf.py
        MM doc/index.rst
        MM doc/so **   ****  and a whole bunch more

**Comment by twinkie0101** [comment]
I am having the same issue.  I am using an rpi 4 running 21.2.0.  Command received and attempt to pull feed is made but no audio.

**Comment by krisgesling** [comment]
Hey there, I've done a big update of the News Skill that fixes this. It's under review and barring any major issues should be out early this week. You can find it on this branch here if you want to give it a test run: 
https://github.com/MycroftAI/skill-npr-news/tree/bugfix/rm-curl

**Comment by Olzeke51** [comment]
this is'nt working:::
***@***.*** ~]$ ssh -p 8222 ***@***.***
(.venv) ***@***.***:~$ msm install
https://github.com/MycroftAI/skill-npr-news/tree/bugfix/rm-curl
INFO - building SkillEntry objects for all skills
WARNING - No such default skill: mycroft-pandora
WARNING - No such default skill: mycroft-pandora
INFO - Downloading skill:
https://github.com/MycroftAI/skill-npr-news/tree/bugfix/rm-curl
INFO - Problem performing action. Restoring skill to previous state...
INFO - invalidating skills cache
CloneException:
  stderr: 'Cloning into '/tmp/tmpyni1lf4d'...
fatal: repository '
https://github.com/MycroftAI/skill-npr-news/tree/bugfix/rm-curl/' not found
'
(.venv) ***@***.***:~$```

**Comment by krisgesling** [comment]
Hey sorry, I should have given some better instructions. You want to use `git checkout` to switch to the feature branch. So on your Mycroft device run:
```
cd /opt/mycroft/skills/mycroft-npr-news.mycroftai
git checkout bugfix/rm-curl
```
