### ISSUE TITLE
Mycroft listens in on the news

### ISSUE THREAD

**Issue by mattiasgiese** [MycroftAI/skill-npr-news#2]
After mycroft (Mark-1, production image from 2017/07/30) fetches and plays the news it won't stop listening for the wake word and will either:
- listen continuously and do nothing
- listen in and ask for clarification because it did not understand the command
- listen in and actually do something (for example playing the news, resulting in NPR inception :-D)

At the moment i simply presume that mycroft is overly sensitive if the user changed the wake word.
I am not sure where or how this could be fixed, i just wanted to document this behaviour.

**Comment by mattiasgiese** [comment]
Some issues seem to be already fixed in #1  :-)

**Comment by forslund** [comment]
Do you mean you get false triggers when news is playing? Or that it never stops listening?  or both.

**Comment by mattiasgiese** [comment]
I get false and also positive triggers. Mycroft will listen until the news anchor stops talking for a bit.

**Comment by kjcole** [comment]
Today I had the experience Mycroft interpreting the NPR broadcast as telling Mycroft to record for a very long time... Since I didn't hear what Mycroft's response to that was, I was quite startled when much later, out of the blue Mycroft said "Stopping audio recording"... Sure enough, the little bugger had been bugging the room for a good length of time.

**Comment by penrods** [comment]
I'm afraid this is a limitation of the wake-word technology, not really a bug in the skill.  Same happens with songs, etc.

Since this is a know limitation that should be dealt with at the hardware (most likely in the mic) or core level, should we still leave this issue open?

**Comment by krisgesling** [comment]
Closing for the reasons outlined in the comment above.
