### ISSUE TITLE
Should /tmp/stream be hardened against people doing tricky things with race conditions?

### ISSUE THREAD

**Issue by detrout** [MycroftAI/skill-npr-news#46]
The path for the socket is hard coded in tmp, I've seen a lot of security announcements that involve trying to avoiding race conditions triggered because of predictable files in /tmp

Maybe it'd be better to use tempfile.mkstemp to make a random file as needed or, since it looks like the file is a socket maybe just use the user's private /run/user/ directory?

**Comment by forslund** [comment]
Hi, thanks for flagging this. You're probably right about it.

A temp-filename is probably the way to go. We shouldn't really hardcode the location either, instead use the `get_cache_directory()` function provided by `mycroft.util`. That way the /tmp or/run/user location can be determined by the installation using the standard config files.

**Comment by krisgesling** [comment]
Have shifted the stream to the cache directory with the latest update, see [commit 8b1cfb9](https://github.com/MycroftAI/skill-npr-news/commit/8b1cfb96b7e3d43336c6b465d6b971b1b98e7630).

**Comment by krisgesling** [comment]
Hi there, with the stream moved to the cache directory, this seems closable.

Feel free to reopen if you disagree, and thanks again for flagging it.
