### ISSUE TITLE
The Dutch NOS news doesn't work

### ISSUE THREAD

**Issue by PureTryOut** [MycroftAI/skill-npr-news#74]
Seems the URL played (http://news.nixxfm.nl:81/nieuws.mp3) requires a log in.

**Comment by krisgesling** [comment]
thanks for reporting, looks like they've added this very recently and indicates that they're not keen on the stream being used externally so we'll remove it.

**Comment by PureTryOut** [comment]
To bad, I like the NOS :cry: Hopefully there is a different source for it somewhere.
