### ISSUE TITLE
Can't ask for a news source from a different location

### ISSUE THREAD

**Issue by PureTryOut** [MycroftAI/skill-npr-news#75]
Even if I ask "give me the news from BBC", it still tries to tell me the news from NOS in the Netherlands.

**Comment by forslund** [comment]
Is it a vocab issue? Does `play bbc` work?

**Comment by PureTryOut** [comment]
`play bbc` does work yes.

**Comment by forslund** [comment]
Thanks for verifying, but yeah. the vocab should be extended to cover your case, it's a fairly normal sounding query

**Comment by PureTryOut** [comment]
Sadly even the example in the README doesn't work, "Play the BBC news".
