### ISSUE TITLE
curl - messing things up

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/skill-npr-news#99]
I was adding more streams and came across examples where curl messes things up...

i think curl should not be used at all, why cant the audio service handle the streams?

i assume this is for compatibility with the simple backend, but in that case curl should be baked in into it, I am using vlc and find the curl usage quite bad

suggestion:
- add http/https support directly to simple audio backend using curl
- remove curl usage across skills
- make vlc the default backend

workaround: https://github.com/MycroftAI/skill-npr-news/pull/102/files#diff-8e2c1f727276d30ced72fa67cb848772a9802162bec39b42a8df5359fd063a4cR180

**Comment by krisgesling** [comment]
I agree, we do want to move all playback centrally so that the system can know what audio is being output at any given time. 

I'm also in favor of making VLC the default. It runs everywhere and handles almost everything.
